# baixa a imagem
FROM ubuntu:latest

# RUN apt-get update && apt-get install vim -y

ENTRYPOINT [ "echo", "Cante !!!\n" ]

# no terminal faz a impressão 
CMD ["Eu sei que vai dar merda\nMas faço mesmo assim\nEu sei como começa, mas ninguém sabe o fim\n..."]

# comando
# docker build -t teste/ubuntu-print .
# docker run --rm teste/ubuntu-print: 
