# baixa a imagem
FROM ubuntu:latest

ENTRYPOINT [ "echo", "Cante !!!" ]

# no terminal faz a impressão 
CMD ["echo","Eu sei que vai da merda mas faço mesmo assim... "]


# comando
# docker build -t teste/ubuntu-print .
# docker run --rm teste/ubuntu-print: 